import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import DashboardWrapper from "./dashboardWrapper"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "MKSTOCK",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link rel="icon" href="https://s3-inventory-management-mkabha.s3.us-east-2.amazonaws.com/logo.png" />
      <body className={inter.className}>
        <DashboardWrapper>{children}</DashboardWrapper></body>
    </html>
  );
}
